import { Inter, Tinos } from "next/font/google"; // Importing the necessary Google Fonts
import "./globals.css";

// Configuring Inter font
const inter = Inter({
  variable: "--font-inter",      // This will create a CSS variable for Inter
  subsets: ["latin"],            // Including the Latin subset for Inter
  weight: ["100", "200", "300", "400", "500", "600", "700"], // Defining all weights needed for Inter
  display: "swap",               // Ensures text uses fallback font until Inter is loaded
});

// Configuring Tinos font
const tinos = Tinos({
  variable: "--font-tinos",      // This will create a CSS variable for Tinos
  subsets: ["latin"],            // Including the Latin subset for Tinos
  weight: ["400", "700"],        // Defining the regular (400) and bold (700) weights for Tinos
  display: "swap",               // Ensures text uses fallback font until Tinos is loaded
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${tinos.variable} antialiased`} // Applying the fonts globally
      >
        {children}
      </body>
    </html>
  );
}
